from __future__ import annotations

import matplotlib

matplotlib.use("Agg")

import math
from pathlib import Path
from unittest.mock import MagicMock, patch

import matplotlib.pyplot as plt
import pytest

from src.plotting._helpers import (
    extract_all_round_metrics,
    extract_metrics_by_round,
    extract_per_client_metric,
    extract_round_stats,
    get_run_name,
    get_run_params,
)


def make_run(
    metrics: dict[str, float] | None = None,
    params: dict[str, str] | None = None,
    run_id: str = "abcdef12",
    run_name: str | None = "test_run",
) -> MagicMock:
    run = MagicMock()
    run.data.metrics = metrics or {}
    run.data.params = params or {}
    run.info.run_id = run_id
    run.info.run_name = run_name
    return run


# ---------------------------------------------------------------------------
# _helpers — get_run_name
# ---------------------------------------------------------------------------


class TestGetRunName:
    def test_custom_name(self) -> None:
        run = make_run(run_name="my_experiment")
        assert get_run_name(run) == "my_experiment"

    def test_autogenerated_name_calm(self) -> None:
        run = make_run(run_name="calm-dancer-123", run_id="aabbccdd1122")
        assert get_run_name(run) == "aabbccdd"

    def test_autogenerated_name_youthful(self) -> None:
        run = make_run(run_name="youthful-sky-456", run_id="aabbccdd1122")
        assert get_run_name(run) == "aabbccdd"

    def test_no_name(self) -> None:
        run = make_run(run_name=None, run_id="aabbccdd1122")
        assert get_run_name(run) == "aabbccdd"

    def test_empty_name(self) -> None:
        run = make_run(run_name="", run_id="aabbccdd1122")
        assert get_run_name(run) == "aabbccdd"


# ---------------------------------------------------------------------------
# _helpers — extract_metrics_by_round
# ---------------------------------------------------------------------------


class TestExtractMetricsByRound:
    def test_basic(self) -> None:
        run = make_run(
            metrics={
                "round_0_server_loss": 0.8,
                "round_1_server_loss": 0.5,
                "round_2_server_loss": 0.3,
            }
        )
        rounds, vals = extract_metrics_by_round(run, "server_loss")
        assert rounds == [0, 1, 2]
        assert vals == [0.8, 0.5, 0.3]

    def test_no_matching_metrics(self) -> None:
        run = make_run(metrics={"round_0_accuracy": 0.9})
        rounds, vals = extract_metrics_by_round(run, "server_loss")
        assert rounds == []
        assert vals == []

    def test_underscore_metric_name(self) -> None:
        run = make_run(
            metrics={
                "round_0_accuracy": 0.9,
                "round_1_accuracy": 0.95,
            }
        )
        rounds, vals = extract_metrics_by_round(run, "accuracy")
        assert rounds == [0, 1]
        assert vals == [0.9, 0.95]

    def test_unsorted_keys(self) -> None:
        run = make_run(
            metrics={
                "round_2_server_loss": 0.3,
                "round_0_server_loss": 0.8,
                "round_1_server_loss": 0.5,
            }
        )
        rounds, vals = extract_metrics_by_round(run, "server_loss")
        assert rounds == [0, 1, 2]

    def test_single_metric(self) -> None:
        run = make_run(metrics={"round_5_epsilon": 1.2})
        rounds, vals = extract_metrics_by_round(run, "epsilon")
        assert rounds == [5]
        assert vals == [1.2]


# ---------------------------------------------------------------------------
# _helpers — extract_all_round_metrics
# ---------------------------------------------------------------------------


class TestExtractAllRoundMetrics:
    def test_multiple_metrics(self) -> None:
        run = make_run(
            metrics={
                "round_0_server_loss": 0.8,
                "round_1_server_loss": 0.5,
                "round_0_accuracy": 0.9,
                "round_1_accuracy": 0.95,
            }
        )
        result = extract_all_round_metrics(run)
        assert "server_loss" in result
        assert "accuracy" in result
        assert result["server_loss"] == ([0, 1], [0.8, 0.5])

    def test_empty(self) -> None:
        run = make_run(metrics={})
        result = extract_all_round_metrics(run)
        assert result == {}


# ---------------------------------------------------------------------------
# _helpers — extract_per_client_metric
# ---------------------------------------------------------------------------


class TestExtractPerClientMetric:
    def test_valid_client(self) -> None:
        run = make_run(
            metrics={
                "round_0_client_1_epsilon": 1.0,
                "round_1_client_1_epsilon": 2.0,
            }
        )
        rounds, vals = extract_per_client_metric(run, 1, "epsilon")
        assert rounds == [0, 1]
        assert vals == [1.0, 2.0]

    def test_different_client_id(self) -> None:
        run = make_run(
            metrics={
                "round_0_client_0_epsilon": 0.5,
                "round_0_client_1_epsilon": 1.0,
            }
        )
        rounds, vals = extract_per_client_metric(run, 1, "epsilon")
        assert rounds == [0]
        assert vals == [1.0]

    def test_no_match(self) -> None:
        run = make_run(metrics={"round_0_client_1_epsilon": 1.0})
        rounds, vals = extract_per_client_metric(run, 99, "epsilon")
        assert rounds == []
        assert vals == []


# ---------------------------------------------------------------------------
# _helpers — extract_round_stats
# ---------------------------------------------------------------------------


class TestExtractRoundStats:
    def test_basic(self) -> None:
        run = make_run(
            metrics={
                "round_0_epsilon_mean": 2.0,
                "round_0_epsilon_std": 0.5,
                "round_1_epsilon_mean": 1.5,
                "round_1_epsilon_std": 0.3,
            }
        )
        rounds, stats = extract_round_stats(run, "epsilon")
        assert rounds == [0, 1]
        assert stats["mean"] == [2.0, 1.5]
        assert stats["std"] == [0.5, 0.3]

    def test_no_stats(self) -> None:
        run = make_run(metrics={"round_0_epsilon": 1.0})
        rounds, stats = extract_round_stats(run, "epsilon")
        assert rounds == []
        assert stats == {}

    def test_multi_word_stat_name(self) -> None:
        run = make_run(
            metrics={
                "round_0_server_loss_mean": 0.5,
                "round_0_server_loss_std": 0.1,
                "round_1_server_loss_mean": 0.3,
                "round_1_server_loss_std": 0.05,
            }
        )
        rounds, stats = extract_round_stats(run, "server_loss")
        assert rounds == [0, 1]
        assert stats["mean"] == [0.5, 0.3]
        assert stats["std"] == [0.1, 0.05]

    def test_partial_aggs(self) -> None:
        run = make_run(
            metrics={
                "round_0_epsilon_mean": 2.0,
                "round_1_epsilon_mean": 1.5,
                "round_1_epsilon_std": 0.3,
            }
        )
        rounds, stats = extract_round_stats(run, "epsilon")
        assert rounds == [0, 1]
        import math

        assert stats["mean"] == [2.0, 1.5]
        assert math.isnan(stats["std"][0])
        assert stats["std"][1] == 0.3


# ---------------------------------------------------------------------------
# _helpers — get_run_params
# ---------------------------------------------------------------------------


class TestGetRunParams:
    def test_basic(self) -> None:
        run = make_run(params={"key1": "val1", "key2": "val2"})
        result = get_run_params(run)
        assert result == {"key1": "val1", "key2": "val2"}

    def test_empty(self) -> None:
        run = make_run(params={})
        result = get_run_params(run)
        assert result == {}


# ---------------------------------------------------------------------------
# convergence — plot_convergence
# ---------------------------------------------------------------------------


class TestPlotConvergence:
    def test_success(self) -> None:
        run = make_run(
            metrics={
                "round_0_server_loss": 0.8,
                "round_1_server_loss": 0.5,
                "round_0_accuracy": 0.6,
                "round_1_accuracy": 0.8,
            }
        )
        with patch("src.plotting.convergence.get_run_by_id", return_value=run):
            from src.plotting.convergence import plot_convergence

            fig = plot_convergence("test_id")
        assert len(fig.axes) == 2
        assert fig.axes[0].get_xlabel() == "Round"
        assert fig.axes[0].get_ylabel() == "Loss"
        assert fig.axes[1].get_xlabel() == "Round"
        assert fig.axes[1].get_ylabel() == "Accuracy"
        plt.close(fig)

    def test_no_data(self) -> None:
        run = make_run(metrics={})
        with patch("src.plotting.convergence.get_run_by_id", return_value=run):
            from src.plotting.convergence import plot_convergence

            with pytest.raises(ValueError, match="No round metrics found"):
                plot_convergence("test_id")

    def test_partial_loss(self) -> None:
        run = make_run(
            metrics={
                "round_0_accuracy": 0.9,
                "round_1_accuracy": 0.95,
            }
        )
        with patch("src.plotting.convergence.get_run_by_id", return_value=run):
            from src.plotting.convergence import plot_convergence

            with pytest.warns(UserWarning, match="No server_loss data"):
                fig = plot_convergence("test_id")
        assert len(fig.axes) == 1
        plt.close(fig)

    def test_partial_accuracy(self) -> None:
        run = make_run(
            metrics={
                "round_0_server_loss": 0.8,
                "round_1_server_loss": 0.5,
            }
        )
        with patch("src.plotting.convergence.get_run_by_id", return_value=run):
            from src.plotting.convergence import plot_convergence

            with pytest.warns(UserWarning, match="No accuracy data"):
                fig = plot_convergence("test_id")
        assert len(fig.axes) == 1
        plt.close(fig)

    def test_save_path(self, tmp_path: Path) -> None:
        run = make_run(
            metrics={
                "round_0_server_loss": 0.8,
                "round_0_accuracy": 0.6,
            }
        )
        path = tmp_path / "convergence.png"
        with patch("src.plotting.convergence.get_run_by_id", return_value=run):
            from src.plotting.convergence import plot_convergence

            fig = plot_convergence("test_id", save_path=path)
        assert path.exists()
        assert path.stat().st_size > 0
        plt.close(fig)

    def test_nan_loss_does_not_corrupt_xaxis(self) -> None:
        metrics: dict[str, float] = {
            "round_0_server_loss": 2.3,
            "round_1_server_loss": 1e10,
            **{f"round_{r}_server_loss": math.nan for r in range(2, 51)},
            **{f"round_{r}_accuracy": 0.5 for r in range(0, 51)},
        }
        run = make_run(metrics=metrics)
        with patch("src.plotting.convergence.get_run_by_id", return_value=run):
            from src.plotting.convergence import plot_convergence

            fig = plot_convergence("test_id")
        ax_loss, ax_acc = fig.axes
        assert ax_loss.get_xlim()[0] <= 0
        assert ax_loss.get_xlim()[1] >= 50
        assert ax_acc.get_xlim()[0] <= 0
        assert ax_acc.get_xlim()[1] >= 50
        plt.close(fig)


# ---------------------------------------------------------------------------
# privacy — plot_client_epsilon_distribution
# ---------------------------------------------------------------------------


class TestPlotClientEpsilonDistribution:
    def test_success(self) -> None:
        run = make_run(
            metrics={
                "round_0_client_0_epsilon": 0.5,
                "round_1_client_0_epsilon": 0.8,
                "round_2_client_0_epsilon": 0.6,
                "round_0_client_1_epsilon": 1.0,
                "round_1_client_1_epsilon": 1.2,
                "round_2_client_1_epsilon": 0.9,
                "round_2_client_0_remaining_budget": 248.1,
                "round_2_client_1_remaining_budget": 246.9,
                "round_2_client_0_cumulative_epsilon": 1.9,
                "round_2_client_1_cumulative_epsilon": 3.1,
                "round_0_epsilon_mean": 0.75,
                "round_0_epsilon_std": 0.25,
                "round_1_epsilon_mean": 1.0,
                "round_1_epsilon_std": 0.2,
                "round_2_epsilon_mean": 0.75,
                "round_2_epsilon_std": 0.15,
            },
            params={"federated.num_rounds": "5"},
        )
        with patch("src.plotting.privacy.get_run_by_id", return_value=run):
            from src.plotting.privacy import plot_client_epsilon_distribution

            fig = plot_client_epsilon_distribution("test_id")
        assert len(fig.axes) == 2
        assert fig.axes[0].get_xlabel() == "Client ID"
        assert fig.axes[1].get_xlabel() == "Round"
        assert fig.axes[1].get_title() == "Epsilon Expended per Round"
        assert len(fig.axes[1].lines) >= 5
        assert len(fig.axes[1].collections) == 1
        plt.close(fig)

    def test_success_legacy(self) -> None:
        run = make_run(
            metrics={
                "round_1_client_0_epsilon": 1.0,
                "round_1_client_1_epsilon": 2.0,
                "round_2_client_0_epsilon": 1.5,
                "round_2_client_1_epsilon": 2.5,
            }
        )
        with patch("src.plotting.privacy.get_run_by_id", return_value=run):
            from src.plotting.privacy import plot_client_epsilon_distribution

            fig = plot_client_epsilon_distribution("test_id")
        assert len(fig.axes) == 2
        assert fig.axes[0].get_xlabel() == "Client ID"
        assert fig.axes[1].get_xlabel() == "Epsilon (\u03b5)"
        plt.close(fig)

    def test_no_data(self) -> None:
        run = make_run(metrics={})
        with patch("src.plotting.privacy.get_run_by_id", return_value=run):
            from src.plotting.privacy import plot_client_epsilon_distribution

            with pytest.raises(ValueError, match="No per-client privacy metrics found"):
                plot_client_epsilon_distribution("test_id")

    def test_save_path(self, tmp_path: Path) -> None:
        run = make_run(
            metrics={
                "round_0_client_0_epsilon": 0.5,
                "round_1_client_0_epsilon": 0.8,
                "round_1_client_0_remaining_budget": 248.7,
                "round_1_client_0_cumulative_epsilon": 1.3,
            },
        )
        path = tmp_path / "client_eps.png"
        with patch("src.plotting.privacy.get_run_by_id", return_value=run):
            from src.plotting.privacy import plot_client_epsilon_distribution

            fig = plot_client_epsilon_distribution("test_id", save_path=path)
        assert path.exists()
        plt.close(fig)


# ---------------------------------------------------------------------------
# privacy — plot_cumulative_privacy_budget
# ---------------------------------------------------------------------------


class TestPlotCumulativePrivacyBudget:
    def test_success(self) -> None:
        run = make_run(
            metrics={
                "round_0_client_0_cumulative_epsilon": 1.0,
                "round_1_client_0_cumulative_epsilon": 2.0,
                "round_0_client_1_cumulative_epsilon": 0.5,
                "round_1_client_1_cumulative_epsilon": 1.0,
            }
        )
        with patch("src.plotting.privacy.get_run_by_id", return_value=run):
            from src.plotting.privacy import plot_cumulative_privacy_budget

            fig = plot_cumulative_privacy_budget("test_id")
        assert len(fig.axes) == 1
        assert fig.axes[0].get_xlabel() == "Round"
        assert fig.axes[0].get_ylabel() == "Cumulative Epsilon (\u03b5)"
        plt.close(fig)

    def test_no_data(self) -> None:
        run = make_run(metrics={})
        with patch("src.plotting.privacy.get_run_by_id", return_value=run):
            from src.plotting.privacy import plot_cumulative_privacy_budget

            with pytest.raises(ValueError, match="No cumulative privacy metrics found"):
                plot_cumulative_privacy_budget("test_id")

    def test_save_path(self, tmp_path: Path) -> None:
        run = make_run(metrics={"round_0_client_0_cumulative_epsilon": 1.0})
        path = tmp_path / "cumulative.png"
        with patch("src.plotting.privacy.get_run_by_id", return_value=run):
            from src.plotting.privacy import plot_cumulative_privacy_budget

            fig = plot_cumulative_privacy_budget("test_id", save_path=path)
        assert path.exists()
        plt.close(fig)


# ---------------------------------------------------------------------------
# comparison — plot_comparison_convergence
# ---------------------------------------------------------------------------


class TestPlotComparisonConvergence:
    def test_success_two_runs(self) -> None:
        run1 = make_run(
            metrics={
                "round_0_server_loss": 0.8,
                "round_1_server_loss": 0.5,
                "round_0_accuracy": 0.6,
                "round_1_accuracy": 0.8,
            }
        )
        run2 = make_run(
            metrics={
                "round_0_server_loss": 0.9,
                "round_1_server_loss": 0.6,
                "round_0_accuracy": 0.5,
                "round_1_accuracy": 0.7,
            }
        )
        fake_runs = {"run1": run1, "run2": run2}
        with patch(
            "src.plotting.comparison.get_run_by_id",
            side_effect=lambda rid: fake_runs[rid],
        ):
            from src.plotting.comparison import plot_comparison_convergence

            fig = plot_comparison_convergence(["run1", "run2"], labels=["A", "B"])
        assert len(fig.axes) == 2
        assert fig.axes[0].get_title() == "Server Loss vs Round"
        assert fig.axes[1].get_title() == "Accuracy vs Round"
        plt.close(fig)

    def test_no_data(self) -> None:
        empty = make_run(metrics={})
        with patch("src.plotting.comparison.get_run_by_id", return_value=empty):
            from src.plotting.comparison import plot_comparison_convergence

            with pytest.raises(ValueError, match="No convergence metrics"):
                plot_comparison_convergence(["run1"], labels=["A"])

    def test_partial_loss(self) -> None:
        run = make_run(
            metrics={
                "round_0_accuracy": 0.9,
                "round_1_accuracy": 0.95,
            }
        )
        with patch("src.plotting.comparison.get_run_by_id", return_value=run):
            from src.plotting.comparison import plot_comparison_convergence

            with pytest.warns(UserWarning, match="No server_loss data"):
                fig = plot_comparison_convergence(["run1"], labels=["A"])
        # Only accuracy data → 1 subplot
        assert len(fig.axes) == 1
        assert fig.axes[0].get_title() == "Accuracy vs Round"
        plt.close(fig)

    def test_partial_accuracy(self) -> None:
        run = make_run(
            metrics={
                "round_0_server_loss": 0.8,
                "round_1_server_loss": 0.5,
            }
        )
        with patch("src.plotting.comparison.get_run_by_id", return_value=run):
            from src.plotting.comparison import plot_comparison_convergence

            with pytest.warns(UserWarning, match="No accuracy data"):
                fig = plot_comparison_convergence(["run1"], labels=["A"])
        # Only loss data → 1 subplot
        assert len(fig.axes) == 1
        assert fig.axes[0].get_title() == "Server Loss vs Round"
        plt.close(fig)

    def test_custom_labels(self) -> None:
        run = make_run(
            metrics={
                "round_0_server_loss": 0.8,
                "round_0_accuracy": 0.6,
            }
        )
        with patch("src.plotting.comparison.get_run_by_id", return_value=run):
            from src.plotting.comparison import plot_comparison_convergence

            fig = plot_comparison_convergence(["run1"], labels=["My Run"])
        legends = [ax.get_legend() for ax in fig.axes if ax.get_legend()]
        assert len(legends) == 2
        plt.close(fig)

    def test_save_path(self, tmp_path: Path) -> None:
        run = make_run(
            metrics={
                "round_0_server_loss": 0.8,
                "round_0_accuracy": 0.6,
            }
        )
        path = tmp_path / "comparison_conv.png"
        with patch("src.plotting.comparison.get_run_by_id", return_value=run):
            from src.plotting.comparison import plot_comparison_convergence

            fig = plot_comparison_convergence(["run1"], labels=["A"], save_path=path)
        assert path.exists()
        plt.close(fig)


# ---------------------------------------------------------------------------
# comparison — plot_comparison_privacy
# ---------------------------------------------------------------------------


class TestPlotComparisonPrivacy:
    def test_success(self) -> None:
        run1 = make_run(
            metrics={
                "round_0_epsilon_mean": 1.0,
                "round_0_epsilon_std": 0.2,
                "round_1_epsilon_mean": 2.0,
                "round_1_epsilon_std": 0.3,
            }
        )
        run2 = make_run(
            metrics={
                "round_0_epsilon_mean": 1.5,
                "round_0_epsilon_std": 0.1,
                "round_1_epsilon_mean": 2.5,
                "round_1_epsilon_std": 0.4,
            }
        )
        fake_runs = {"run1": run1, "run2": run2}
        with patch(
            "src.plotting.comparison.get_run_by_id",
            side_effect=lambda rid: fake_runs[rid],
        ):
            from src.plotting.comparison import plot_comparison_privacy

            fig = plot_comparison_privacy(["run1", "run2"], labels=["A", "B"])
        # Only per-round data present → 1 subplot
        assert len(fig.axes) == 1
        ax = fig.axes[0]
        assert ax.get_xlabel() == "Round"
        assert ax.get_ylabel() == "Per-Round Epsilon (ε)"
        assert ax.get_title() == "Per-Round Privacy Cost"
        legends = ax.get_legend()
        assert legends is not None
        assert len(legends.get_texts()) == 2
        assert len(ax.collections) == 2
        plt.close(fig)

    def test_success_both_metrics(self) -> None:
        run1 = make_run(
            metrics={
                "round_0_epsilon_mean": 1.0,
                "round_0_epsilon_std": 0.2,
                "round_1_epsilon_mean": 2.0,
                "round_1_epsilon_std": 0.3,
                "round_0_cumulative_epsilon_mean": 1.0,
                "round_1_cumulative_epsilon_mean": 3.0,
            }
        )
        run2 = make_run(
            metrics={
                "round_0_epsilon_mean": 1.5,
                "round_0_epsilon_std": 0.1,
                "round_1_epsilon_mean": 2.5,
                "round_1_epsilon_std": 0.4,
                "round_0_cumulative_epsilon_mean": 1.5,
                "round_1_cumulative_epsilon_mean": 4.0,
            }
        )
        fake_runs = {"run1": run1, "run2": run2}
        with patch(
            "src.plotting.comparison.get_run_by_id",
            side_effect=lambda rid: fake_runs[rid],
        ):
            from src.plotting.comparison import plot_comparison_privacy

            fig = plot_comparison_privacy(["run1", "run2"], labels=["A", "B"])
        assert len(fig.axes) == 2
        ax_per, ax_cum = fig.axes
        assert ax_per.get_ylabel() == "Per-Round Epsilon (ε)"
        assert ax_per.get_title() == "Per-Round Privacy Cost"
        assert ax_cum.get_ylabel() == "Cumulative Epsilon (ε)"
        assert ax_cum.get_title() == "Cumulative Privacy Cost"
        assert len(ax_per.collections) == 2
        plt.close(fig)

    def test_no_std(self) -> None:
        run1 = make_run(
            metrics={
                "round_0_epsilon_mean": 1.0,
                "round_0_epsilon_std": 0.2,
                "round_1_epsilon_mean": 2.0,
                "round_1_epsilon_std": 0.3,
            }
        )
        fake_runs = {"run1": run1}
        with patch(
            "src.plotting.comparison.get_run_by_id",
            side_effect=lambda rid: fake_runs[rid],
        ):
            from src.plotting.comparison import plot_comparison_privacy

            fig = plot_comparison_privacy(["run1"], labels=["A"], show_std=False)
        assert len(fig.axes) == 1
        assert len(fig.axes[0].collections) == 0
        plt.close(fig)

    def test_no_data(self) -> None:
        empty = make_run(metrics={})
        with patch("src.plotting.comparison.get_run_by_id", return_value=empty):
            from src.plotting.comparison import plot_comparison_privacy

            with pytest.raises(ValueError, match="No privacy metrics"):
                plot_comparison_privacy(["run1"], labels=["A"])

    def test_save_path(self, tmp_path: Path) -> None:
        run = make_run(metrics={"round_0_epsilon_mean": 1.0})
        path = tmp_path / "comparison_privacy.png"
        with patch("src.plotting.comparison.get_run_by_id", return_value=run):
            from src.plotting.comparison import plot_comparison_privacy

            fig = plot_comparison_privacy(["run1"], labels=["A"], save_path=path)
        assert path.exists()
        plt.close(fig)


# ---------------------------------------------------------------------------
# bo — plot_metric_vs_epsilon
# ---------------------------------------------------------------------------


class TestPlotMetricVsEpsilon:
    def test_success(self) -> None:
        run = make_run(
            metrics={
                "round_0_client_0_epsilon": 1.0,
                "round_1_client_0_epsilon": 2.0,
                "round_0_client_0_utility_loss": 0.5,
                "round_1_client_0_utility_loss": 0.3,
            }
        )
        with patch("src.plotting.bo.get_run_by_id", return_value=run):
            from src.plotting.bo import plot_metric_vs_epsilon

            fig = plot_metric_vs_epsilon("test_id", client_id=0)
        # Main scatter + colorbar
        assert len(fig.axes) == 2
        assert fig.axes[0].get_xlabel() == "Epsilon (\u03b5)"
        plt.close(fig)

    def test_warmup_phase(self) -> None:
        run = make_run(
            metrics={
                "round_0_client_0_epsilon": 1.0,
                "round_1_client_0_epsilon": 2.0,
                "round_2_client_0_epsilon": 3.0,
                "round_0_client_0_utility_loss": 0.5,
                "round_1_client_0_utility_loss": 0.4,
                "round_2_client_0_utility_loss": 0.3,
            }
        )
        with patch("src.plotting.bo.get_run_by_id", return_value=run):
            from src.plotting.bo import plot_metric_vs_epsilon

            fig = plot_metric_vs_epsilon("test_id", client_id=0, warmup_rounds=1)
        legends = fig.axes[0].get_legend()
        assert legends is not None
        legend_texts = [t.get_text() for t in legends.get_texts()]
        assert "Warm-up" in legend_texts
        assert "BO" in legend_texts
        plt.close(fig)

    def test_no_round_data(self) -> None:
        run = make_run(metrics={"round_0_client_0_utility_loss": 0.5})
        with patch("src.plotting.bo.get_run_by_id", return_value=run):
            from src.plotting.bo import plot_metric_vs_epsilon

            with pytest.raises(ValueError, match="No data for client 0"):
                plot_metric_vs_epsilon("test_id", client_id=0)

    def test_no_metric_data(self) -> None:
        run = make_run(metrics={"round_0_client_0_epsilon": 1.0})
        with patch("src.plotting.bo.get_run_by_id", return_value=run):
            from src.plotting.bo import plot_metric_vs_epsilon

            with pytest.raises(ValueError, match="No data for client 0"):
                plot_metric_vs_epsilon("test_id", client_id=0, metric="nonexistent")

    def test_save_path(self, tmp_path: Path) -> None:
        run = make_run(
            metrics={
                "round_0_client_0_epsilon": 1.0,
                "round_0_client_0_utility_loss": 0.5,
            }
        )
        path = tmp_path / "metric_vs_eps.png"
        with patch("src.plotting.bo.get_run_by_id", return_value=run):
            from src.plotting.bo import plot_metric_vs_epsilon

            fig = plot_metric_vs_epsilon("test_id", client_id=0, save_path=path)
        assert path.exists()
        plt.close(fig)
